
q1=[
    [1,"The members of the Rajya Sabha are elected by elected","A.members of the Legislative Assembly","B.members of Lok Sabha","C.members of Rajya Sabha","D.members of Supreme court",1],
    [2,"Total number of High Courts in India is?","A.24","B.25", "C.26","D.27",1],
    [3,"Who was the first Indian Women President of the United Nations General Assembly.","A.Vijay Lakshmi Pandit","B.Lata Devi","C.Indira Gandhi","D.Sarojini Devi",1],
    [4,'"Which one of the following article deals with the appointment of the Prime Minister and other ministers?',"A.Article 76","B.Article 74","C.Article 75 ","D.Article 72",3],
    [5,'The Prime Minister is appointed by which one of the following?',"A.Attorney general of India","B.President","C.Vice-president", "D.Chief justice of India",2],
    [6,'The Supreme Court of India at present contains the following number of Judges?'," A.25 judges"," B.31 judges", "C.20 judges","D.30 judges",2],
    [7,"Who among the following appoints the Chief Justice and other Judges of the Supreme Court?","A.Prime minister","B.Vice-president","C.Home minister","D.President",4],
    [8,"Which of the following are the powers of the Supreme Court?","A.Original and Appellate Jurisdiction","B.Appointment of ad-hoc judges","C.Judicial review","D.All The Above",4],
    [9,"Mr. T.S. Thakur is the ...................Chief Justice of India.","A.41st","B.42nd","C.43rd","D.44th",3],
    [10,"The executive power of the Union is vested in which one of the below?","A.Prime Minister","B.Home Minister","C.Vice President","D.President",4],
    [11,"When was the first Parliamentary Forum on Water Conservation and Management constituted?","A.1950","B.2005","C.1970","D.1985",2],
    [12,"When was the first Parliamentary Forum on Youth constituted?","A.2010","B.2008","C.2006","D.1985",3],
    [13,"The independence of Judiciary”  in Indian constitution is taken from.","A.Britain","B.USA","C.South Africa","C.Austalia",1],
    [14,"Which of the following article of the Indian Constitution deals with the constitution of the Parliament of India?","A.Article 73","B.Article 78","C.Article 79","D.Article 72",3],
    [15,"How many number of members are nominated by the President to the Rajya sabha?","A.20","B.18","C.12","D.15",3],
    [16,"who among the following was the first chief justice of india and assumed office on 26th jan.1950?","A.meher chand mahajand","B.patanjli sastri","C.harilal kania","D.BK mukherjea",3],
    [17,"which constitutional artical lays down the provision for a national commission for SC and ST?","A.artical 337","B.artical 334","C.artical 338","D.artical 339",3],
    [18,"which community gets special provision for central service in artical 336?","A.sikh community","B.muslim community","C.hindu community","D.anglo-indian community",4],
    [19,"national commision for SC and ST shall be made by which constitutional institution?","A.paelament","B.Executive","C.judiciary","D.state legislature",1],
    [20,"under constitutional artical 343, which is the official language of the union?","A.urdu","B.hindi","C.english","D.B&c",4],
    [21,"which constitutional artical define muncipalities?","A.artical 243P","B.artical 243Q","C.artical 243T","D.artical 343U",1],
    [22,"the constitution of the india , was drafted and enacted in which language?","A.hindi","B.english","C.tamil","D.telugu",2],
    [23,"total no. of schedule in constitution of india is :?","A.22","B.17","C.97","D.12",4],
    [24,"constitution of india was enacted by the constitunet assembly on:?","A.26 january 1950","B.26 november 1949","C.20 nov. 1950","D.20 january 1949",2],
    [25,"constitution of india cam into effect on:?","A.january 1950","B.26 nov.1949","C.20 nov.1950","D.20 january 1949",1],
    [26,"total no. of six fundamental rights in constitutional of india is:?","A.12","B.5","C.6","D.8",3],
    [27,"indian indipandance act,passed by the british parliment on:?","A.18 july 1947","B.20 july 1947","C.14 august1947","D.20 july 1946",1],
    [28,"how many member can be nominated to the rajya sabha by president in india?","A.10","B.12","C.14","D.18",2],
    [29,"what is the minimun age for appointment as a governer?","A.35 years","B.40 years","C.25 years","D.30 years",1],
    [30,"chief minister of a state is responsible to ","A.prime minister","B.rajya sanha","C.legistative assembly","D.governer",3],]
    
    

